#!/usr/bin/env bash

# give sudo permission for mightybuilder user
# user creation is postponed to the entrypoint,
# so we can create a user with the same id as the host
echo 'mightybuilder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install tini
TINI_VERSION="v0.18.0"
curl -Ls https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -o /opt/docker/bin/tini
chmod +x /opt/docker/bin/tini

INTEL_URL="https://www.dropbox.com/s/75nmbp19l25fm6x/parallel_studio_xe_2018_update2_professional_edition.tgz"
cd Deps && \
curl -Ls $INTEL_URL | tar -xz -C parallel_studio_xe_2018_update2_professional_edition --strip-components=1 && \
cd parallel_studio_xe_2018_update2_professional_edition && \
./install.sh --silent=silent-parallel-studio.cfg && \
cd - && \
rm -rf parallel_studio_xe_2018_update2_professional_edition

# Install recent CMake
cmake_url="https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz"
target_path="/opt/docker/cmake"
mkdir -p $target_path && \
curl -Ls $cmake_url | tar -xz -C $target_path --strip-components=1 && \
rm -rf cmake-3.11.4-Linux-x86_64.tar.gz

# Create lucky group
groupadd -g 32766 lucky
